### ISSUE TITLE
Getting the following error when I try to push - can anyone see what I'm doing wrong?

### ISSUE THREAD

**Issue by marcz2007** [watson-developer-cloud/tone-analyzer-nodejs#160]
When pushing from manifest to org, I get an error message:
     marcwatts$ ibmcloud app push songtone
    Invoking 'cf push songtone'...
    
    Pushing from manifest to org marc.jwatts@gmail.com / space dev as marc.jwatts@gmail.com...
    Using manifest file /Users/marcwatts/Desktop/mxw817/tone/tone-analyzer-nodejs-master/manifest.yml
    Getting app info...
    Service instance my-tone-analyzer-service not found
    FAILED
    
Here is my manifest file: 
    ---
    declared-services:
      my-tone-analyzer-service:
        label: tone_analyzer
        plan: lite
    applications:
    - services:
      - my-tone-analyzer-service
      name: songtone
      command: npm start
      path: .
      instances: 2
      memory: 256MB
    
What is going wrong here?

**Comment by germanattanasio** [comment]
Remove the `my-tone-analyzer-service` from the `manifest.yml`

**Comment by marcz2007** [comment]
Thank you, that solved that problem! Although now it is saying that I have a memory restriction? Any ideas how to solve that?

Creating app with these attributes...
+ name:        songtone
  path:        /Users/marcwatts/Desktop/mxw817/tone/tone-analyzer-nodejs-master
+ command:     npm start
+ instances:   2
+ memory:      256M
  routes:
+   songtone.eu-gb.mybluemix.net

Creating app songtone...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 73.78 KiB / 73.78 KiB [============================================] 100.00% 2s

Waiting for API to complete processing files...

Staging app and tracing logs...
You have exceeded your organization's memory limit: app requested more memory than available
FAILED

**Comment by cclauss** [comment]
Jack up the memory in [manifest.yml](https://github.com/watson-developer-cloud/tone-analyzer-nodejs/blob/master/manifest.yml#L13)?

**Comment by marcz2007** [comment]
Ah amazing thank you for your help! I changed the memory in the manifest file and that seemed to work :)

**Comment by marcz2007** [comment]
When I try to create a new free cluster it says that I cannot on my account and that I should upgrade to a pay-as-you go subscription - is this meant to happen when the cluster is supposedly free?

**Comment by germanattanasio** [comment]
Yes you need a pay-as-you-go account
