### ISSUE TITLE
Failed No org and space targeted

### ISSUE THREAD

**Issue by iampeterbanjo** [watson-developer-cloud/tone-analyzer-nodejs#32]
The error message

```
FAILED
No org and space targeted, use 'cf target -o ORG -s SPACE' to target an org and space
```

was caused because my account region was in EU not US in step 4.

If the docs noted that for the EU end point the command should be `cf api https://api.eu-gb.bluemix.net` that would help.

**Comment by germanattanasio** [comment]
Can you create a pull request with this ?

**Comment by nfriedly** [comment]
We should probably link to more thorough instructions hosted elsewhere (since this applies to all of our sample apps)

**Comment by iampeterbanjo** [comment]
Ok. I made a pull request.

**Comment by germanattanasio** [comment]
thanks!

**Comment by germanattanasio** [comment]
that's a good idea @nfriedly, but the instructions aren't always the same so we need to see how to make the generic part in a central place and the specific part here
