### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by agustincasamayor** [watson-developer-cloud/tone-analyzer-nodejs#34]
Once you have analyzed some text, the "3 categories of tones" link that appears under the Output title is not working. 
The specific documentation that link points at was removed from the documentation apparently. 
The actual fix for this would be adding that documentation back and link it appropriately;

In the meantime one of two things can be done:
· Remove that link altogether;
· Replace the destination url with this one that works: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/#overview

![image](https://cloud.githubusercontent.com/assets/10199975/13187062/d44d8856-d727-11e5-8fb3-4385290d52b7.png)

**Comment by jzhang300** [comment]
I'm gonna go with Option 2

**Comment by jzhang300** [comment]
109a7533c502651c23951d4dc8f3020929883045
