### ISSUE TITLE
Fix "Challenges" visual treatment

### ISSUE THREAD

**Issue by kathrynmcelroy** [watson-developer-cloud/tone-analyzer-nodejs#5]
<img width="994" alt="screen shot 2015-09-23 at 3 23 52 pm" src="https://cloud.githubusercontent.com/assets/5400092/10057675/1f58a038-6207-11e5-8ac4-8abea1d44c0d.png">

The UI was updated to indicate which words do or do not have synonyms, but "challenges" has synonyms and has the wrong visual treatment.

**Comment by germanattanasio** [comment]
new release so we close this
