### ISSUE TITLE
Changes to document-level tone instructions

### ISSUE THREAD

**Issue by dezzie** [watson-developer-cloud/tone-analyzer-nodejs#56]
These are now in two parts, to correspond with emotion's probability-based scores and writing/social's raw score system. The text goes below.

<img width="1070" alt="screen shot 2016-05-13 at 1 22 10 pm" src="https://cloud.githubusercontent.com/assets/1301932/15260251/4ca8e856-191b-11e6-8255-f47cf9d479d8.png">

- [x] below emotion:

> The Emotion graph represents the likelihood that an emotion tone is present in the text. [Learn more](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#emotional).

- [x] below writing and social tendencies:

> The Writing Style and Social Tendencies graphs represent the amount of a writing or social tone present in the text. [Learn more](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#social).

**Comment by jzhang300** [comment]
How would these descriptions look responsively when the graphs stack with each other on smaller screen sizes?

Currently, it stacks like this responsively:

[Emotion Graph]
[Writing Style Graph]
[Social Graph]
[Emotion Description]
[Writing and Social Description]

I think we can keep this order, but we'll need to change the wordings slightly to...

"The emotion graph represents the likelihood that an emotion tone is present in the text. Learn more."
"The Writing Style and Social graphs represent the raw amount that each tone is present in the text sample."

What do you think @dezzie ?

**Comment by jzhang300** [comment]
Take a look at issue #67 and continue discussion from there.

**Comment by dezzie** [comment]
I edited this issue with your writing changes @jzhang300 and @kcheat  suggests that the text go above, not below, the graphs.
