### ISSUE TITLE
Check all highlighted words for accuracy

### ISSUE THREAD

**Issue by kathrynmcelroy** [watson-developer-cloud/tone-analyzer-nodejs#6]
Since "challenges" has the wrong visual treatment (https://github.com/watson-developer-cloud/tone-analyzer-nodejs/issues/5), please check and make sure none of the other words are mis-labeled.

**Comment by germanattanasio** [comment]
@herchu is this issue getting fixed with your latest changes ?

**Comment by germanattanasio** [comment]
new release so we close this as it's invalid now
