### ISSUE TITLE
Suggested text changes

### ISSUE THREAD

**Issue by kcheat** [watson-developer-cloud/tone-analyzer-nodejs#67]
Change top level sentence from this:
![image](https://cloud.githubusercontent.com/assets/8249758/15226436/b079d0b4-1850-11e6-922a-714dab13ab9b.png)
to this:
Discover and understand how emotions are coming across, the social tendencies that are being expressed, and how your writing style is coming across in your content.

Remove the section under Choose Content (I don't think this is necessary because it is just reiterating the header Choose Content, and it doesn't really need to be clarified):
![image](https://cloud.githubusercontent.com/assets/8249758/15226474/dc970ce8-1850-11e6-9b3c-b18402c719a0.png)

Change the content of the Output from:
![image](https://cloud.githubusercontent.com/assets/8249758/15226606/69c693d6-1851-11e6-84dd-519932ab8696.png)
to this:
Use the document level analysis to get a sense of the overall tone of the document, and use the sentence level analysis to identify the strongest tones of specific parts of the content.

Remove the inline help under Document Level and Sentence Level (this is now covered generally under the output): 
![image](https://cloud.githubusercontent.com/assets/8249758/15226667/adae2c4e-1851-11e6-9531-ef0367abb1ca.png)
![image](https://cloud.githubusercontent.com/assets/8249758/15226675/b636f9e0-1851-11e6-892a-0dbbcef09bd6.png)

Add inline help sections under Document level Emotion Summary, Language Summary and Social summary:
- Emotional tone is inferred from different types of emotions and feelings that people express in their language. [Learn more...] http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#emotional
- Language tone describes whether a persons writing style will be perceived as analytical, confident, and tentative.[Learn more...] http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#language
- Social tone measures the social tendencies that are coming through in the content.  [Learn more...] http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#social

Remove raw score from the summary headings (does not really express clear info):
![image](https://cloud.githubusercontent.com/assets/8249758/15226873/a82a6f8e-1852-11e6-95d8-90f65f940b13.png)

----------

- [x] Change top level description to "Discover and understand how emotions are coming across, the social tendencies that are being expressed, and how your writing style is coming across in your content."
- [x] Remove the section under Choose Content
- [x] Change the content of the Output to "Use the document level analysis to get a sense of the overall tone of the document, and use the sentence level analysis to identify the strongest tones of specific parts of the content."
- [x] Add inline help sections under Document level Emotion Summary, Language Summary and Social summary
- [x] Remove raw score from the summary headings

**Comment by jzhang300** [comment]
@kcheat @dezzie 

Since we removed the Output paragraph altogether in issue #54, I'm thinking we can split the output description ("Use the document level analysis to get a sense of the overall tone of the document, and use the sentence level analysis to identify the strongest tones of specific parts of the content.") into their respective Document-level tone and Sentence-level tone sections.

There was also Document level inline help sections specified in issue #56.  The way it's done here has more consistency.

How should we resolve these?

**Comment by kcheat** [comment]
@jzhang300 splitting it out into their respective Document-level tone and Sentence-level tone sections sounds good to me and I think both proposed methods of document level inline help solve the same issue so I am all for picking whichever one is easier to implement

**Comment by dezzie** [comment]
do we have time for this by monday?

**Comment by dezzie** [comment]
closing this issue because it's covered in other issues or we're done editing the overall copy. Last bit that needs to be done are tooltips for graph headers, that issue is here #71
