### ISSUE TITLE
Document level tone tool tip changes for scores only

### ISSUE THREAD

**Issue by kcheat** [watson-developer-cloud/tone-analyzer-nodejs#68]
On the Document level tables, instead of the tool tips just having the score, they should also have an explanation of the score.
For example instead of this:
![image](https://cloud.githubusercontent.com/assets/8249758/15227319/9620b580-1854-11e6-9da8-f316f02ca75f.png)
This:
0.90 - more likely to be perceived as concerned, frustrated, angry, passionate, upset, stressed, insecure, or impulsive.

What each score should return:

**Emotion**
Replace [emotion] with angry, disgusted, afraid, joyful, and sad

0 - 0.25 - Not likely to be perceived as [emotion]
0.25 - 0.75 - Moderately likely to be perceived as [emotion]
0.75 - 1 - Highly likely to be perceived as [emotion]

**Language**
- Analytical 
  - 0 - 0.25 - the text contains little or no evidence of analytical tone
  - 0.25 - 0.75 - the text is somewhat likely to be perceived as intellectual, rational, systematic, emotionless, or impersonal
  - 0.75 - 1 - more likely to be perceived as intellectual, rational, systematic, emotionless, or impersonal
-  Confidence 
  - 0 - 0.25 - the text contains little or no evidence of confidence in tone
  - 0.25 - 0.75 - the text is somewhat likely to be perceived as assured, collected, hopeful, or egotistical
  - 0.75 - 1 - more likely to be perceived as as assured, collected, hopeful, or egotistical
- Tentative
  - 0 - 0.25 - the text contains little or no evidence of tentativeness in tone
  - 0.25 - 0.75 - the text is somewhat likely to be perceived as questionable, doubtful, limited, or debatable
  - 0.75 - 1 - more likely to be perceived as as questionable, doubtful, limited, or debatable

**Social**
- Openness
  - 0 - 0.25 - more likely to be perceived as no-nonsense, straightforward, blunt, or preferring tradition and the obvious over the complex, ambiguous, and subtle
  - 0.25 - 0.75 - somewhat likely to be perceived as no-nonsense, straightforward, blunt, or preferring tradition and the obvious over the complex, ambiguous, and subtle
  - 0.50 - 0.75 - somewhat likely to be perceived as intellectual, curious, emotionally-aware, imaginative, willing to try new things, appreciating beauty, or open to change
  - 0.75 - 1 - more likely to be perceived as intellectual, curious, emotionally-aware, imaginative, willing to try new things, appreciating beauty, or open to change
- Conscientiousness
  - 0 - 0.25 - more likely to be perceived as spontaneous, laid-back, reckless, unmethodical, remiss, or disorganized
  - 0.25 - 0.75 - somewhat likely to be perceived as spontaneous, laid-back, reckless, unmethodical, remiss, or disorganized
  - 0.50 - 0.75 - somewhat likely to be perceived as disciplined, dutiful, achievement-striving, confident, driven, or organized
  - 0.75 - 1 - more likely to be perceived as disciplined, dutiful, achievement-striving, confident, driven, or organized
- Extroversion
  - 0 - 0.25 - more likely to be perceived as independent, timid, introverted, restrained, boring, or dreary
  - 0.25 - 0.75 - somewhat likely to be perceived as independent, timid, introverted, restrained, boring, or dreary
  - 0.50 - 0.75 - somewhat likely to be perceived as engaging, seeking attention, needy, assertive, outgoing, sociable, cheerful, excitement-seeking, or busy
  - 0.75 - 1 - more likely to be perceived as engaging, seeking attention, needy, assertive, outgoing, sociable, cheerful, excitement-seeking, or busy
- Agreeableness
  - 0 - 0.25 - more likely to be perceived as selfish, uncaring, uncooperative, self-interested, confrontational, skeptical, or arrogant
  - 0.25 - 0.75 - somewhat likely to be perceived as selfish, uncaring, uncooperative, self-interested, confrontational, skeptical, or arrogant
  - 0.50 - 0.75 - somewhat likely to be perceived as caring, sympathetic, cooperative, compromising, trustworthy, or humble
  - 0.75 - 1 - more likely to be perceived as caring, sympathetic, cooperative, compromising, trustworthy, or humble
- Emotional range
  - 0 - 0.25 - more likely to be perceived as calm, bland, content, relaxed, unconcerned, or careful
  - 0.25 - 0.75 - somewhat likely to be perceived as calm, bland, content, relaxed, unconcerned, or careful
  - 0.50 - 0.75 - somewhat likely to be perceived as concerned, frustrated, angry, passionate, upset, stressed, insecure, or impulsive
  - 0.75 - 1 - more likely to be perceived as concerned, frustrated, angry, passionate, upset, stressed, insecure, or impulsive

---
- [ ] Emotion
- [ ] Language
- [ ] Social

**Comment by jzhang300** [comment]
In issues #51, #52, and #53, we got rid of the hover tooltips for scores and displayed the scores staticly next to the bar.

We can probably proceed by adding the hover tooltips to the new static scores.

@kcheat @dezzie what do u guys think?

**Comment by kcheat** [comment]
They both sound like good ideas to me @jzhang300

**Comment by germanattanasio** [comment]
CLosing this since it refers to the old demo
