### ISSUE TITLE
Document-level inline help for graphs headers only

### ISSUE THREAD

**Issue by dezzie** [watson-developer-cloud/tone-analyzer-nodejs#71]
Add tooltips with links to the headers of each document-level graph:
- [ ] Emotion
  
  > Emotional tone is inferred from different types of emotions and feelings that people express in their language. [Learn more](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#emotional)
- [ ] Writing Style
  
  > Writing style tone describes whether a persons writing style will be perceived as analytical, confident, and tentative. [Learn more](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#language)
- [ ] Social tendencies

> Social tendencies tones measure personality traits that are coming through in the content. [Learn more](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/understanding-tone.shtml#social)
- [ ] links should open in new window

**Comment by jzhang300** [comment]
@dezzie I'm a little confused, does this override #56?
