### ISSUE TITLE
edit names of tone for spanish

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/tone-analyzer-nodejs#80]
sudo nano /home/felipe/tone-analyzer-nodejs/public/js/components/App.js
##
          score: 0,
          tone_id: 'Anger',
          tone_name: 'Enojo',
          tone_category_id: 'emotion_tone',
          tone_category_name: 'Emotion Tone'
##

But not working
How solved?

**Comment by herchu** [comment]
Felipe, you can use a http header `Accept-Language: es` to get the tone names in Spanish directly from the APIs. I guess this is what you need (not too clear from your question).

**Comment by johnfelipe** [comment]
where can find that?
Or where put in tone-analyzer-nodejs demo?

**Comment by johnfelipe** [comment]
Where add or edit 'Accept-Language: es'?

**Comment by johnfelipe** [comment]
me again where put `Accept-Language: es`

**Comment by germanattanasio** [comment]
```js
// Create the service wrapper
var toneAnalyzer = watson.tone_analyzer({
  url: 'https://gateway.watsonplatform.net/tone-analyzer/api/',
  username: '<username>',
  password: '<password>',
  version_date: '2016-05-19',
  version: 'v3',
  headers: {
   'Accept-Language': 'es'
  }
});
```

**Comment by johnfelipe** [comment]
var toneAnalyzer = watson.tone_analyzer({
	  url: 'https://gateway.watsonplatform.net/tone-analyzer/api/',
	  username: 'e9f75e44-491a-47e1-bbe3-5a9889366758',
	  password: 'my password',
	  version_date: '2016-05-19',
	  version: 'v3',
	  headers: {
	   'Accept-Language': 'es'
	  }
	});

`npm install` and `pm2 reload server.js`

and not work

**Comment by germanattanasio** [comment]
I don't know what pm2 is and I'm sure it's not part of this sample.

**Comment by johnfelipe** [comment]
pm2 is same like npm server.js

**Comment by johnfelipe** [comment]
// Create the service wrapper
	var toneAnalyzer = watson.tone_analyzer({
	  url: 'https://gateway.watsonplatform.net/tone-analyzer/api/',
	  username: 'e9f75e44-491a-47e1-bbe3-5a9889366758',
	  password: 'xxxxxxxx',
	  version_date: '2016-05-19',
	  version: 'v3',
	  headers: {
	   'Accept-Language': 'es'
	  }
	});

not working

**Comment by johnfelipe** [comment]
http://181.135.20.181:3012/
is not working
git pull
and nothing yet to spanish

**Comment by johnfelipe** [comment]
var toneAnalyzer = watson.tone_analyzer({
	  url: 'https://gateway.watsonplatform.net/tone-analyzer/api/',
	  username: 'xxxxx',
	  password: 'xxxxxx',
	  version_date: '2016-05-19',
	  version: 'v3',
	  headers: {
	   'Accept-Language': 'es'
	  }
	});

Is not working
http://181.135.20.181:3012/

Pls help

**Comment by kognate** [comment]
Can you give a little more information about what exactly is not working? If your getting error messages can you attach them with the issue?

**Comment by johnfelipe** [comment]
is not error only i cant see in spanish, pls put a spanish text in **Tu Propio Texto**

http://181.135.20.181:3012/

![analizador](https://cloud.githubusercontent.com/assets/428820/18250450/2533191c-7349-11e6-911b-a4a03ef58871.png)

**Comment by germanattanasio** [comment]
The `node-sdk` version that was used here was a little bit old.  I updated the dependency in the `package.json` and was able to get Spanish results from the API.

On the other hand,  this demo doesn't support Spanish. Parts of the UI need the emotions/tones to be in English.

**Comment by johnfelipe** [comment]
version_date: '2016-05-19',
  version: 'v3',
  headers: {
   'Accept-Language': 'es'

i pull, update

![analizadordos](https://cloud.githubusercontent.com/assets/428820/18256039/8840a0c0-7375-11e6-85d5-ef30f4cdbffe.png)

is not working

**Comment by germanattanasio** [comment]
As I said in my comment above. The demo doesn't work in English. The API does.
