### ISSUE TITLE
I think IBM has grammar and spell and other style checker. Please add into DEMO. Thanks

### ISSUE THREAD

**Issue by asd-and-Rizzo** [watson-developer-cloud/tone-analyzer-nodejs#98]
I could use http://grammarly.com/ and https://tone-analyzer-demo.mybluemix.net/. But I hope IBM has http://grammarly.com/ build in, please add support for this. This will be ultimate combo to sell IBM Watson to my management.

**Comment by ehdsouza** [comment]
This is a feature request for tone analyzer api.
