### ISSUE TITLE
Consider updating travis.yml to deploy to Bluemix

### ISSUE THREAD

**Issue by todkap** [watson-developer-cloud/tone-analyzer-nodejs#99]
There is a Bluemix Deployer that could be used to streamline the development flow w/ deploy to Bluemix.  Might be worth considering.  [Bluemix CloudFoundry Deployer](https://docs.travis-ci.com/user/deployment/bluemixcloudfoundry/)

**Comment by germanattanasio** [comment]
Hi Todd, thanks for the suggestion.

We are currently using the Bluemix CLI along with a script to provide blue-green deployments.
